/* ColourDiam remastered — data layer
   Loads REAL product data synced from www.colourdiam.com public storefront
   (data/diamonds.json + data/jewelry.json, generated by scripts/sync_colourdiam.py).
   No mock inventory. Media served over HTTPS from images/auto-sync/. */

const CDData = {
  colors: [
    { name: "Black", slug: "black", img: "images/loosestones/Black.png", desc: "Mysterious, bold and completely opaque fancy black diamonds." },
    { name: "Blue", slug: "blue", img: "images/loosestones/Blue.png", desc: "One of nature's rarest colours, prized for its serene depth." },
    { name: "Brown", slug: "brown", img: "images/loosestones/Brown.png", desc: "Chocolate and champagne hues with warm sophistication." },
    { name: "Gray", slug: "gray", img: "images/loosestones/Gray.png", desc: "Cool, contemporary greys with a silvery shimmer." },
    { name: "Green", slug: "green", img: "images/loosestones/Green.png", desc: "A rare botanical green caused by natural radiation exposure." },
    { name: "Orange", slug: "orange", img: "images/loosestones/Orange.png", desc: "Sunset-orange diamonds full of fiery brilliance." },
    { name: "Pink", slug: "pink", img: "images/loosestones/pink.png", desc: "Feminine, romantic and among the most coveted in the world." },
    { name: "Purple", slug: "purple", img: "images/loosestones/Purple.png", desc: "An extraordinarily rare violet-tinged fancy colour." },
    { name: "Red", slug: "red", img: "images/loosestones/Red.png", desc: "The rarest of all diamonds — only a handful ever mined." },
    { name: "Violet", slug: "violet", img: "images/loosestones/Violet.png", desc: "Deep violet hues with an unmistakable royal presence." },
    { name: "White", slug: "white", img: "images/loosestones/White.png", desc: "Classic colourless brilliance — timeless and versatile." },
    { name: "Yellow", slug: "yellow", img: "images/loosestones/Yellow.png", desc: "Golden canary diamonds that radiate warmth and joy." }
  ],

  testimonials: [
    { text: "I'd been eyeing a fancy pink diamond for months and finally found the right one here. The ring exceeded photos — the color is even more vivid in person. Shipping to Singapore was smooth too.", name: "Priya M.", location: "Singapore" },
    { text: "Bought a yellow diamond pendant as an anniversary gift. My wife hasn't taken it off since. The certification paperwork gave me total peace of mind about authenticity.", name: "James Carter", location: "London, UK" },
    { text: "What stood out was the personal attention — someone actually walked me through clarity and cut differences over a video call before I committed to my earrings.", name: "Natcha S.", location: "Bangkok, Thailand" },
    { text: "I collect colored stones and was skeptical about buying loose diamonds online. ColourDiam's GIA certs matched exactly what was described. Will be back for a blue diamond next.", name: "David Lindqvist", location: "Stockholm, Sweden" },
    { text: "The custom design process for my engagement ring took about three weeks start to finish. They sent progress photos at each stage, which I really appreciated.", name: "Ananya R.", location: "Mumbai, India" },
    { text: "Ordered a bracelet for my mother's birthday — arrived beautifully packaged and right on schedule. The brown diamond setting is exactly the warm tone we wanted.", name: "Michael Tan", location: "Kuala Lumpur, Malaysia" }
  ],

  diamonds: [],
  jewelry: [],
  _loaded: false,

  mediaBase: "images/auto-sync",
  placeholder: "images/auto-sync/assets/img/ColorDiam.png",

  mediaPath: function (p) {
    if (!p) return this.placeholder;
    if (/^(https?:)?\/\//.test(p)) return p;
    if (p.charAt(0) === "/") return this.mediaBase + p;
    return this.mediaBase + "/" + p;
  },

  async load() {
    if (this._loaded) return this;
    const [d, j] = await Promise.all([
      fetch("data/diamonds.json").then(r => r.json()),
      fetch("data/jewelry.json").then(r => r.json())
    ]);
    this.diamonds = d;
    this.jewelry = j;
    this._loaded = true;
    return this;
  },

  featured(count) {
    const featured = [];
    const pick = function (list, n) {
      const arr = list.slice();
      const out = [];
      const idx = new Set();
      while (out.length < n && arr.length) {
        const i = Math.floor(Math.random() * arr.length);
        if (idx.has(i)) { arr.splice(i, 1); continue; }
        idx.add(i);
        out.push(arr[i]);
        arr.splice(i, 1);
      }
      return out;
    };
    const isNew = this.diamonds.filter(d => d.isNew);
    featured.push.apply(featured, pick(isNew.length ? isNew : this.diamonds, Math.min(2, count)));
    const nj = this.jewelry.filter(x => x.isNew);
    featured.push.apply(featured, pick(nj.length ? nj : this.jewelry, count - featured.length));
    return featured.slice(0, count);
  }
};
